Add documentation and tutorial for GEOS-Chem input data on AWS.
geoschem/geos-chem-shared-docs pull request #3
Opened 2024-07-11 20:52 UTC by yidant

- supplemental-guides/geos-chem-input-data-on-aws.rst is the main page.
 - why-on-cloud.rst, data-on-aws.rst and getting-started-aws.rst are sub-pages.

2024-07-12 15:10 UTC, yantosca requested changes
Thanks @yidant!  This looks great.  I've noted a few minor things to change.

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/data-on-aws.rst
> +The GEOS-Chem Input Data is structured into the following main categories (For more information , see `Download input data <https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/download-da
Typo: `information , see` -> `information, see` (delete space)

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/data-on-aws.rst
> +1. :ref:`c1-init-cond` (aka `Restart files <https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/restart-files.html#restart-files>`_)
It's probably better to link to `latest` instead of `stable`, so that any updates to the restart_files page will be rendered.

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/data-on-aws.rst
> +Initial conditions include initial species concentrations (aka `Restart files <https://geos-chem.readthedocs.io/en/stable/gcclassic-user-guide/restart-files.html#restart-files>`_) used to start a GEO
Ditto: stable -> latest

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/geos-chem-input-data-on-aws.rst
> +<https://gchp.readthedocs.io/en/stable/>`_. This includes NASA/GMAO MERRA-2 and GEOS-FP `meteorological products <https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/input-overview.html#m
Ditto stable -> latest for all links

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/getting-started-aws.rst
> +   $ aws s3 ls s3://<resource_name>/
Is the `<resource_name>` not yet established?  We should provide a list of the s3 buckets that they can download from, both the 500TB and the 70TB.

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/getting-started-aws.rst
> +By following this tutorial, you can access and download the GEOS-Chem Input Data on AWS. Next, you can follow the normal `GEOS-Chem Classic <https://geos-chem.readthedocs.io/en/stable/getting-started
Ditto stable -> latest for both links

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/why-on-cloud.rst
> +########
Change title to something like "Why do we store GEOS-Chem data on the cloud?".  I think this sounds a little better.

2024-07-12 15:10 UTC, yantosca commented on supplemental-guides/why-on-cloud.rst
> +<https://gchp.readthedocs.io/en/latest/supplement/setting-up-aws-parallelcluster.html>`_
Add period after link

2024-07-12 18:24 UTC, yantosca approved these changes
Thanks @yidant!  I can merge this into main.  Thanks again!

2024-09-25 19:21 UTC, yidant commented
Hi @yantosca! I updated the s3 bucket resource name in these docs. A new merge is needed. The s3 bucket is almost ready!

2024-10-15 17:05 UTC, yidant commented
Hi @yantosca! Another update on AWS S3 Explorer link is added!

2024-10-15 17:51 UTC, yantosca commented
Thanks @yidant!

2024-10-15 18:22 UTC, merged